### ISSUE TITLE
Add Card Image Tags for OpenGraph and Twitter

### ISSUE THREAD

**Issue by angel1254mc** [WiNGHacks/WiNGHacks-Website#38]
Hi WiNGHacks dev team 😄

I was sharing the link to the homepage on Discord and noticed that the card that gets generated doesn't include an image. It's not a big deal but I figured I should mention it here in case it's something you think is worth adding  :)

![image](https://github.com/WiNGHacks/WiNGHacks-Website/assets/59091763/d43ef8c6-5ea5-4bb9-974b-2335c6a7ffcc)

If you add something like this to the `index.html` `<head>...</head>` section I think an image should pop up on the card

```html
<!-- Open Graph -->
    <meta property="og:type" content="website" />
    <meta property="og:url" content="%PUBLIC_URL%" />
    <meta property="og:title" content="WiNGHacks" />
    <meta property="og:description" content="University of Florida's first hackathon for women and nonbinary students." />
    <meta property="og:image" content="%PUBLIC_URL%/WiNGHacks_card.webp" />

    <!-- Twitter -->
    <meta property="twitter:card" content="summary_large_image" />
    <meta property="twitter:url" content="%PUBLIC_URL%" />
    <meta property="twitter:title" content="WiNGHacks" />
    <meta property="twitter:description" content="University of Florida's first hackathon for women and nonbinary students." />
    <meta property="twitter:image" content="%PUBLIC_URL%/WiNGHacks_card.webp" />
```
Where "WiNGHacks_card.webp" is the image you want on the card.

Thank you so much for helping make WiNGHacks a reality!

**Comment by christinealin7771** [comment]
Thank you for bringing this up! We will address this!

**Comment by mariapasaylo** [comment]
Thank you for noticing this detail. Made updates to reflect this change. I will check if the image shows up in our next deployment.
